### ISSUE TITLE
when i run the program with spark-submit i get errors

### ISSUE THREAD

**Issue by arezki1990** [stefanobaghino/spark-twitter-stream-example#1]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/streaming/twitter/TwitterUtils$
	at me.baghino.spark.intro.TwitterExampleBase$class.$init$(TwitterExampleBase.scala:32)
	at me.baghino.spark.intro.TwitterExample$.<init>(TwitterExample.scala:10)
	at me.baghino.spark.intro.TwitterExample$.<clinit>(TwitterExample.scala)
	at me.baghino.spark.intro.TwitterExample.main(TwitterExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.streaming.twitter.TwitterUtils$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

**Comment by stefanobaghino** [comment]
Hi, thanks for reaching out on this. How did you package the job?

**Comment by stefanobaghino** [comment]
I added the possibility to package the job with [sbt-assembly](https://github.com/sbt/sbt-assembly).

To run:
* pull the new code
* provide the authentication keys as described in `README.md`
* run `sbt assembly` from the command line
* submit the resulting artifact

You can find the precise commands on `README.md`.

The `broadcast-var` branch has been rebased accordingly.

Thanks for reporting the issue and feel free to re-open it should the problem not be solved.

**Comment by stefanobaghino** [comment]
I noticed that I forgot to make resources available for submission but I just patched the code and tested it on a local deployment.
