### ISSUE TITLE
i have an other , this time in the program  , figure out that pleas in the fellowing 

### ISSUE THREAD

**Issue by arezki1990** [stefanobaghino/spark-twitter-stream-example#6]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.streaming.StreamingContext$.toPairDStreamFunctions(Lorg/apache/spark/streaming/dstream/DStream;Lscala/reflect/ClassTag;Lscala/reflect/ClassTag;Lscala/math/Ordering;)Lorg/apache/spark/streaming/dstream/PairDStreamFunctions;
	at me.baghino.spark.intro.TwitterExample$.delayedEndpoint$me$baghino$spark$intro$TwitterExample$1(TwitterExample.scala:23)
	at me.baghino.spark.intro.TwitterExample$delayedInit$body.apply(TwitterExample.scala:10)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at me.baghino.spark.intro.TwitterExample$.main(TwitterExample.scala:10)
	at me.baghino.spark.intro.TwitterExample.main(TwitterExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by stefanobaghino** [comment]
What version of Spark is the installation you are running a job on?

**Comment by arezki1990** [comment]
i have the last version 2.0.2

**Comment by stefanobaghino** [comment]
It is very unlikely that this job will work. I wrote it more than a year ago and depends on Spark 1.2.1. I have been able to test it on Spark 1.4 for your latest issues. Feel free to fork this and adapt it to the latest versions of Spark. Have fun!

**Comment by stefanobaghino** [comment]
@arezki1990 I've found some time to refresh the project to support Spark 2.x, hope it can be useful now. Make sure you read the README as I changed a couple of things.
