### ISSUE TITLE
Exception on submit

### ISSUE THREAD

**Issue by eaorak** [stefanobaghino/spark-twitter-stream-example#7]
Thanks for this nice example. I'm getting the error below after calling:

```
spark-submit \
  --class me.baghino.spark.intro.TwitterExample \
  --master local[n] \
  target/scala-2.11/spark-twitter-stream-example-assembly-0.0.1.jar
```

Any ideas?

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.streaming.StreamingContext$.toPairDStreamFunctions(Lorg/apache/spark/streaming/dstream/DStream;Lscala/reflect/ClassTag;Lscala/reflect/ClassTag;Lscala/math/Ordering;)Lorg/apache/spark/streaming/dstream/PairDStreamFunctions;
	at me.baghino.spark.intro.TwitterExample$.delayedEndpoint$me$baghino$spark$intro$TwitterExample$1(TwitterExample.scala:19)
	at me.baghino.spark.intro.TwitterExample$delayedInit$body.apply(TwitterExample.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at me.baghino.spark.intro.TwitterExample$.main(TwitterExample.scala:6)
	at me.baghino.spark.intro.TwitterExample.main(TwitterExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by stefanobaghino** [comment]
What version are you deploying to?

**Comment by stefanobaghino** [comment]
Closing for lack of feedback, feel free to reopen it should you have more details on the problem.

**Comment by stefanobaghino** [comment]
@eaorak If by chance you were trying to deploy it on a Spark 2.x installation, this example was very old and originally ran on Spark 1.2. I've found some time to refresh the project to support Spark 2.x, hope it can be useful now. Make sure you read the README as I changed a couple of things.

**Comment by eaorak** [comment]
Hi Stefano, I've recently noticed your feedback. I'm using the latest version of Spark (2.0.2). I will try again following new instructions and let you know about the result. Thank you so much.
