### ISSUE TITLE
Error while running example

### ISSUE THREAD

**Issue by gabhi** [stefanobaghino/spark-twitter-stream-example#8]
@stefanobaghino I m getting following error while running exmaple

````
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.streaming.StreamingContext$.toPairDStreamFunctions(Lorg/apache/spark/streaming/dstream/DStream;Lscala/reflect/ClassTag;Lscala/reflect/ClassTag;Lscala/math/Ordering;)Lorg/apache/spark/streaming/dstream/PairDStreamFunctions;
	at me.baghino.spark.intro.TwitterExample$.delayedEndpoint$me$baghino$spark$intro$TwitterExample$1(TwitterExample.scala:23)
	at me.baghino.spark.intro.TwitterExample$delayedInit$body.apply(TwitterExample.scala:10)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at me.baghino.spark.intro.TwitterExample$.main(TwitterExample.scala:10)
	at me.baghino.spark.intro.TwitterExample.main(TwitterExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

````

**Comment by stefanobaghino** [comment]
How did you run the example? Did you deploy it on an existing Spark cluster? If yes, which version?

**Comment by gabhi** [comment]
@stefanobaghino I m new to spark. i ran it on local machine using following command 
````
spark-submit \
  --class me.baghino.spark.intro.TwitterExample \
  target/scala-2.11/spark-twitter-stream-example-assembly-0.0.1.jar
````

spark version  version 2.1.0

scala version 2.11.7

**Comment by stefanobaghino** [comment]
This is a very old example, it was written for Spark 1.2. I think I once ran it on Spark 1.4 or 1.6 but I can't guarantee the version up until this job is compatible. Spark no longer ships with the Twitter APIs, if you want you can fork this repo and use [Apache Bahir](http://bahir.apache.org/docs/spark/current/spark-streaming-twitter/) to make it work on Spark 2.x. Happy hacking! :slightly_smiling_face:

**Comment by stefanobaghino** [comment]
@gabhi I've found some time to refresh the project to support Spark 2.x, hope it can be useful now. Make sure you read the README as I changed a couple of things.
